services:
  - type: web
    name: lvo-ingenierie
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
